"""Tareas Added

Revision ID: 047272387864
Revises: bdc374f108fd
Create Date: 2021-06-09 15:43:19.115886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047272387864'
down_revision = 'bdc374f108fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=1500), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    # ### end Alembic commands ###
