"""Califiaciones Update

Revision ID: 1f96dd5e0703
Revises: fee8c18667da
Create Date: 2021-06-11 16:06:37.185854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f96dd5e0703'
down_revision = 'fee8c18667da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calificacion', sa.Column('id_tarea', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calificacion', 'tarea', ['id_tarea'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calificacion', type_='foreignkey')
    op.drop_column('calificacion', 'id_tarea')
    # ### end Alembic commands ###
